id: I6804E095
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:19:03+00:00'
last_modified: '2022-06-08T09:52:55.596013+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30517
  title: སྨན་སྦྱོར་ནུས་པ་ཕྱོགས་བསྡུས་ཕན་བདེའི་ལེགས་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8E73:
      image_group_id: I1KG21729
      title: ''
      total_pages: 86
      order: 1
      base_file: 8E73.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
