id: P009278
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30517
  title: སྨན་སྦྱོར་ནུས་པ་ཕྱོགས་བསྡུས་ཕན་བདེའི་ལེགས་བཤད།
  author: ''
  volumes:
    a38950b7a75e4331ab29d7b96afdbf9d:
      image_group_id: I1KG21729
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
